name: Build Mj-WhatsApp APK
on:
  push:
    branches:
      - main  # Setiap lo push kodingan ke branch main, APK otomatis dibuat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Robot ini bakal ngebungkus web lo pake tools Bubblewrap (TWA)
      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      # Tahap ini bakal nge-generate file APK asli Android
      - name: Build APK
        run: |
          bubblewrap build --accept_toast_permissions
          
      - name: Upload APK Result
        uses: actions/upload-artifact@v3
        with:
          name: Mj-WhatsApp-Release
          path: ./*.apk
