name: Build Mj-WhatsApp APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4 # Update ke v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Update ke v4
        with:
          node-version: 20

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        # Ditambahkan perintah inisialisasi agar robot tidak bingung
        run: |
          bubblewrap init --manifest=manifest.json --no-interactive
          bubblewrap build --skipSigning

      - name: Upload APK Result
        uses: actions/upload-artifact@v4 # Update ke v4 (Ini yang bikin error tadi)
        with:
          name: Mj-WhatsApp-Release
          path: ./*.apk
          
